sudo: false  
language: java    
jdk: oraclejdk8
cache:  
  directories:
   - $HOME/.m2
   - $HOME/jpm
install: mvn package -B
script: xvfb-run mvn verify -B
after_success:
  - curl -sL https://github.com/jpm4j/jpm4j.installers/raw/master/dist/biz.aQute.jpm.run.jar > ~/.m2/jpm4j.jar
  - java -jar $HOME/.m2/jpm4j.jar -u install com.codacy:codacy-coverage-reporter:assembly
  - $HOME/jpm/bin/codacy-coverage-reporter -l Java -r tests/target/jacoco/report/jacoco.xml
