version: 1.0.{build}
init:
- cmd: 
install:
- cmd: choco install maven -y
cache: C:\Users\appveyor\.m2
build_script:
- cmd: mvn package -B
test_script:
- cmd: mvn verify -B
artifacts:
- path: p2\target\*.zip
  name: Update site
on_finish:
- ps: >-
    $url = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"

    Get-ChildItem "tests/target/surefire-reports/" -Filter *.xml | Foreach-Object{
        (New-Object 'System.Net.WebClient').UploadFile($url, $_.FullName)
    }
