/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package nl.esciencecenter.e3dchem.gpcrdb.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

/**
 * ProteinSimilarity
 */

public class ProteinSimilarity implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("similarity")
  private Integer similarity = null;

  @SerializedName("identity")
  private Integer identity = null;

  @SerializedName("AA")
  private String AA = null;

  public ProteinSimilarity similarity(Integer similarity) {
    this.similarity = similarity;
    return this;
  }

   /**
   * Get similarity
   * @return similarity
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getSimilarity() {
    return similarity;
  }

  public void setSimilarity(Integer similarity) {
    this.similarity = similarity;
  }

  public ProteinSimilarity identity(Integer identity) {
    this.identity = identity;
    return this;
  }

   /**
   * Get identity
   * @return identity
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getIdentity() {
    return identity;
  }

  public void setIdentity(Integer identity) {
    this.identity = identity;
  }

  public ProteinSimilarity AA(String AA) {
    this.AA = AA;
    return this;
  }

   /**
   * Get AA
   * @return AA
  **/
  @ApiModelProperty(required = true, value = "")
  public String getAA() {
    return AA;
  }

  public void setAA(String AA) {
    this.AA = AA;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProteinSimilarity proteinSimilarity = (ProteinSimilarity) o;
    return Objects.equals(this.similarity, proteinSimilarity.similarity) &&
        Objects.equals(this.identity, proteinSimilarity.identity) &&
        Objects.equals(this.AA, proteinSimilarity.AA);
  }

  @Override
  public int hashCode() {
    return Objects.hash(similarity, identity, AA);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProteinSimilarity {\n");
    
    sb.append("    similarity: ").append(toIndentedString(similarity)).append("\n");
    sb.append("    identity: ").append(toIndentedString(identity)).append("\n");
    sb.append("    AA: ").append(toIndentedString(AA)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

