/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package nl.esciencecenter.e3dchem.gpcrdb.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
/**
 * ProteinSimilarity
 */

public class ProteinSimilarity  implements Serializable {
  @SerializedName("similarity")
  private Integer similarity = null;

  @SerializedName("identity")
  private Integer identity = null;

  @SerializedName("AA")
  private String AA = null;

  public ProteinSimilarity similarity(Integer similarity) {
    this.similarity = similarity;
    return this;
  }

   /**
   * Get similarity
   * @return similarity
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getSimilarity() {
    return similarity;
  }

  public void setSimilarity(Integer similarity) {
    this.similarity = similarity;
  }

  public ProteinSimilarity identity(Integer identity) {
    this.identity = identity;
    return this;
  }

   /**
   * Get identity
   * @return identity
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public Integer getIdentity() {
    return identity;
  }

  public void setIdentity(Integer identity) {
    this.identity = identity;
  }

  public ProteinSimilarity AA(String AA) {
    this.AA = AA;
    return this;
  }

   /**
   * Get AA
   * @return AA
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getAA() {
    return AA;
  }

  public void setAA(String AA) {
    this.AA = AA;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProteinSimilarity proteinSimilarity = (ProteinSimilarity) o;
    return Objects.equals(this.similarity, proteinSimilarity.similarity) &&
        Objects.equals(this.identity, proteinSimilarity.identity) &&
        Objects.equals(this.AA, proteinSimilarity.AA);
  }

  @Override
  public int hashCode() {
    return Objects.hash(similarity, identity, AA);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProteinSimilarity {\n");
    
    sb.append("    similarity: ").append(toIndentedString(similarity)).append("\n");
    sb.append("    identity: ").append(toIndentedString(identity)).append("\n");
    sb.append("    AA: ").append(toIndentedString(AA)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

