/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package nl.esciencecenter.e3dchem.gpcrdb.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import nl.esciencecenter.e3dchem.gpcrdb.client.model.Ligand;
import java.io.Serializable;

/**
 * Structure
 */

public class Structure implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("publication_date")
  private String publicationDate = null;

  @SerializedName("preferred_chain")
  private String preferredChain = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("species")
  private String species = null;

  @SerializedName("protein")
  private String protein = null;

  @SerializedName("resolution")
  private Float resolution = null;

  @SerializedName("ligands")
  private List<Ligand> ligands = new ArrayList<>();

  @SerializedName("publication")
  private String publication = null;

  @SerializedName("pdb_code")
  private String pdbCode = null;

  @SerializedName("family")
  private String family = null;

  public Structure publicationDate(String publicationDate) {
    this.publicationDate = publicationDate;
    return this;
  }

   /**
   * Get publicationDate
   * @return publicationDate
  **/
  @ApiModelProperty(required = true, value = "")
  public String getPublicationDate() {
    return publicationDate;
  }

  public void setPublicationDate(String publicationDate) {
    this.publicationDate = publicationDate;
  }

  public Structure preferredChain(String preferredChain) {
    this.preferredChain = preferredChain;
    return this;
  }

   /**
   * Get preferredChain
   * @return preferredChain
  **/
  @ApiModelProperty(required = true, value = "")
  public String getPreferredChain() {
    return preferredChain;
  }

  public void setPreferredChain(String preferredChain) {
    this.preferredChain = preferredChain;
  }

  public Structure type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(required = true, value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public Structure species(String species) {
    this.species = species;
    return this;
  }

   /**
   * Get species
   * @return species
  **/
  @ApiModelProperty(required = true, value = "")
  public String getSpecies() {
    return species;
  }

  public void setSpecies(String species) {
    this.species = species;
  }

  public Structure protein(String protein) {
    this.protein = protein;
    return this;
  }

   /**
   * Get protein
   * @return protein
  **/
  @ApiModelProperty(required = true, value = "")
  public String getProtein() {
    return protein;
  }

  public void setProtein(String protein) {
    this.protein = protein;
  }

  public Structure resolution(Float resolution) {
    this.resolution = resolution;
    return this;
  }

   /**
   * Get resolution
   * @return resolution
  **/
  @ApiModelProperty(required = true, value = "")
  public Float getResolution() {
    return resolution;
  }

  public void setResolution(Float resolution) {
    this.resolution = resolution;
  }

  public Structure ligands(List<Ligand> ligands) {
    this.ligands = ligands;
    return this;
  }

  public Structure addLigandsItem(Ligand ligandsItem) {
    this.ligands.add(ligandsItem);
    return this;
  }

   /**
   * Get ligands
   * @return ligands
  **/
  @ApiModelProperty(required = true, value = "")
  public List<Ligand> getLigands() {
    return ligands;
  }

  public void setLigands(List<Ligand> ligands) {
    this.ligands = ligands;
  }

  public Structure publication(String publication) {
    this.publication = publication;
    return this;
  }

   /**
   * Get publication
   * @return publication
  **/
  @ApiModelProperty(value = "")
  public String getPublication() {
    return publication;
  }

  public void setPublication(String publication) {
    this.publication = publication;
  }

  public Structure pdbCode(String pdbCode) {
    this.pdbCode = pdbCode;
    return this;
  }

   /**
   * Get pdbCode
   * @return pdbCode
  **/
  @ApiModelProperty(required = true, value = "")
  public String getPdbCode() {
    return pdbCode;
  }

  public void setPdbCode(String pdbCode) {
    this.pdbCode = pdbCode;
  }

  public Structure family(String family) {
    this.family = family;
    return this;
  }

   /**
   * Get family
   * @return family
  **/
  @ApiModelProperty(required = true, value = "")
  public String getFamily() {
    return family;
  }

  public void setFamily(String family) {
    this.family = family;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Structure structure = (Structure) o;
    return Objects.equals(this.publicationDate, structure.publicationDate) &&
        Objects.equals(this.preferredChain, structure.preferredChain) &&
        Objects.equals(this.type, structure.type) &&
        Objects.equals(this.species, structure.species) &&
        Objects.equals(this.protein, structure.protein) &&
        Objects.equals(this.resolution, structure.resolution) &&
        Objects.equals(this.ligands, structure.ligands) &&
        Objects.equals(this.publication, structure.publication) &&
        Objects.equals(this.pdbCode, structure.pdbCode) &&
        Objects.equals(this.family, structure.family);
  }

  @Override
  public int hashCode() {
    return Objects.hash(publicationDate, preferredChain, type, species, protein, resolution, ligands, publication, pdbCode, family);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Structure {\n");
    
    sb.append("    publicationDate: ").append(toIndentedString(publicationDate)).append("\n");
    sb.append("    preferredChain: ").append(toIndentedString(preferredChain)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    species: ").append(toIndentedString(species)).append("\n");
    sb.append("    protein: ").append(toIndentedString(protein)).append("\n");
    sb.append("    resolution: ").append(toIndentedString(resolution)).append("\n");
    sb.append("    ligands: ").append(toIndentedString(ligands)).append("\n");
    sb.append("    publication: ").append(toIndentedString(publication)).append("\n");
    sb.append("    pdbCode: ").append(toIndentedString(pdbCode)).append("\n");
    sb.append("    family: ").append(toIndentedString(family)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

