/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package nl.esciencecenter.e3dchem.gpcrdb.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

/**
 * WriteResidueSerializer
 */

public class WriteResidueSerializer implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("sequence_number")
  private Integer sequenceNumber = null;

  @SerializedName("amino_acid")
  private String aminoAcid = null;

  public WriteResidueSerializer sequenceNumber(Integer sequenceNumber) {
    this.sequenceNumber = sequenceNumber;
    return this;
  }

   /**
   * Get sequenceNumber
   * @return sequenceNumber
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getSequenceNumber() {
    return sequenceNumber;
  }

  public void setSequenceNumber(Integer sequenceNumber) {
    this.sequenceNumber = sequenceNumber;
  }

  public WriteResidueSerializer aminoAcid(String aminoAcid) {
    this.aminoAcid = aminoAcid;
    return this;
  }

   /**
   * Get aminoAcid
   * @return aminoAcid
  **/
  @ApiModelProperty(required = true, value = "")
  public String getAminoAcid() {
    return aminoAcid;
  }

  public void setAminoAcid(String aminoAcid) {
    this.aminoAcid = aminoAcid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WriteResidueSerializer writeResidueSerializer = (WriteResidueSerializer) o;
    return Objects.equals(this.sequenceNumber, writeResidueSerializer.sequenceNumber) &&
        Objects.equals(this.aminoAcid, writeResidueSerializer.aminoAcid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sequenceNumber, aminoAcid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WriteResidueSerializer {\n");
    
    sb.append("    sequenceNumber: ").append(toIndentedString(sequenceNumber)).append("\n");
    sb.append("    aminoAcid: ").append(toIndentedString(aminoAcid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

