/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package nl.esciencecenter.e3dchem.gpcrdb.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

/**
 * WriteProteinSerializer
 */

public class WriteProteinSerializer implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("entry_name")
  private String entryName = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("accession")
  private String accession = null;

  @SerializedName("sequence")
  private String sequence = null;

  public WriteProteinSerializer entryName(String entryName) {
    this.entryName = entryName;
    return this;
  }

   /**
   * Get entryName
   * @return entryName
  **/
  @ApiModelProperty(required = true, value = "")
  public String getEntryName() {
    return entryName;
  }

  public void setEntryName(String entryName) {
    this.entryName = entryName;
  }

  public WriteProteinSerializer name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public WriteProteinSerializer accession(String accession) {
    this.accession = accession;
    return this;
  }

   /**
   * Get accession
   * @return accession
  **/
  @ApiModelProperty(value = "")
  public String getAccession() {
    return accession;
  }

  public void setAccession(String accession) {
    this.accession = accession;
  }

  public WriteProteinSerializer sequence(String sequence) {
    this.sequence = sequence;
    return this;
  }

   /**
   * Get sequence
   * @return sequence
  **/
  @ApiModelProperty(required = true, value = "")
  public String getSequence() {
    return sequence;
  }

  public void setSequence(String sequence) {
    this.sequence = sequence;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WriteProteinSerializer writeProteinSerializer = (WriteProteinSerializer) o;
    return Objects.equals(this.entryName, writeProteinSerializer.entryName) &&
        Objects.equals(this.name, writeProteinSerializer.name) &&
        Objects.equals(this.accession, writeProteinSerializer.accession) &&
        Objects.equals(this.sequence, writeProteinSerializer.sequence);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entryName, name, accession, sequence);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WriteProteinSerializer {\n");
    
    sb.append("    entryName: ").append(toIndentedString(entryName)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    accession: ").append(toIndentedString(accession)).append("\n");
    sb.append("    sequence: ").append(toIndentedString(sequence)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

