/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package nl.esciencecenter.e3dchem.gpcrdb.client;

import nl.esciencecenter.e3dchem.gpcrdb.client.ApiException;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ServicesplotApi
 */
public class ServicesplotApiTest {

    private final ServicesplotApi api = new ServicesplotApi();

    
    /**
     * Get SVG source code for a protein&#39;s helix box plot
     *
     * Get SVG source code for a protein&#39;s helix box plot&lt;br/&gt;/plot/helixbox/{entry_name}/&lt;br/&gt;{entry_name} is a protein identifier from Uniprot, e.g. adrb2_human
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void helixBoxGETTest() throws ApiException {
        String entryName = null;
        // Object response = api.helixBoxGET(entryName);

        // TODO: test validations
    }
    
    /**
     * Get SVG source code for a protein&#39;s snake plot
     *
     * Get SVG source code for a protein&#39;s snake plot&lt;br/&gt;/plot/snake/{entry_name}/&lt;br/&gt;{entry_name} is a protein identifier from Uniprot, e.g. adrb2_human
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void snakePlotGETTest() throws ApiException {
        String entryName = null;
        // Object response = api.snakePlotGET(entryName);

        // TODO: test validations
    }
    
}
