/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package nl.esciencecenter.e3dchem.gpcrdb.client;

import nl.esciencecenter.e3dchem.gpcrdb.client.ApiException;
import nl.esciencecenter.e3dchem.gpcrdb.client.model.ProteinSimilarities;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ServicesalignmentApi
 */
public class ServicesalignmentApiTest {

    private final ServicesalignmentApi api = new ServicesalignmentApi();

    
    /**
     * Get a full sequence alignment of a protein family including a consensus sequence
     *
     * Get a full sequence alignment of a protein family including a consensus sequence&lt;br/&gt;/alignment/family/{slug}/&lt;br/&gt;{slug} is a protein family identifier, e.g. 001_001_001
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void familyAlignmentGETTest() throws ApiException {
        String slug = null;
        // Object response = api.familyAlignmentGET(slug);

        // TODO: test validations
    }
    
    /**
     * Get a full sequence alignment of a protein family including a consensus sequence
     *
     * Get a full sequence alignment of a protein family including a consensus sequence&lt;br/&gt;/alignment/family/{slug}/&lt;br/&gt;{slug} is a protein family identifier, e.g. 001_001_001
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void familyAlignmentGET_0Test() throws ApiException {
        String slug = null;
        // Object response = api.familyAlignmentGET_0(slug);

        // TODO: test validations
    }
    
    /**
     * Get a partial sequence alignment of a protein family
     *
     * Get a partial sequence alignment of a protein family&lt;br/&gt;/alignment/family/{slug}/{segments}/&lt;br/&gt;{slug} is a protein family identifier, e.g. 001_001_001&lt;br/&gt;{segments} is a comma separated list of protein segment identifiers and/ or     generic GPCRdb numbers, e.g. TM2,TM3,ECL2,4x50
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void familyAlignmentPartialGETTest() throws ApiException {
        String slug = null;
        String segments = null;
        // Object response = api.familyAlignmentPartialGET(slug, segments);

        // TODO: test validations
    }
    
    /**
     * Get a partial sequence alignment of a protein family
     *
     * Get a partial sequence alignment of a protein family&lt;br/&gt;/alignment/family/{slug}/{segments}/&lt;br/&gt;{slug} is a protein family identifier, e.g. 001_001_001&lt;br/&gt;{segments} is a comma separated list of protein segment identifiers and/ or     generic GPCRdb numbers, e.g. TM2,TM3,ECL2,4x50
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void familyAlignmentPartialGET_0Test() throws ApiException {
        String slug = null;
        String segments = null;
        // Object response = api.familyAlignmentPartialGET_0(slug, segments);

        // TODO: test validations
    }
    
    /**
     * Get a partial sequence alignment of a protein family
     *
     * Get a partial sequence alignment of a protein family&lt;br/&gt;/alignment/family/{slug}/{segments}/{species}&lt;br/&gt;{slug} is a protein family identifier, e.g. 001_001_001&lt;br/&gt;{segments} is a comma separated list of protein segment identifiers and/ or     generic GPCRdb numbers, e.g. TM2,TM3,ECL2,4x50&lt;br/&gt;{species} is a species identifier from Uniprot, e.g. Homo sapiens
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void familyAlignmentPartialSpeciesGETTest() throws ApiException {
        String slug = null;
        String segments = null;
        String latinName = null;
        // Object response = api.familyAlignmentPartialSpeciesGET(slug, segments, latinName);

        // TODO: test validations
    }
    
    /**
     * Get a partial sequence alignment of a protein family
     *
     * Get a partial sequence alignment of a protein family&lt;br/&gt;/alignment/family/{slug}/{segments}/{species}&lt;br/&gt;{slug} is a protein family identifier, e.g. 001_001_001&lt;br/&gt;{segments} is a comma separated list of protein segment identifiers and/ or     generic GPCRdb numbers, e.g. TM2,TM3,ECL2,4x50&lt;br/&gt;{species} is a species identifier from Uniprot, e.g. Homo sapiens
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void familyAlignmentPartialSpeciesGET_0Test() throws ApiException {
        String slug = null;
        String segments = null;
        String latinName = null;
        // Object response = api.familyAlignmentPartialSpeciesGET_0(slug, segments, latinName);

        // TODO: test validations
    }
    
    /**
     * Get a full sequence alignment of two or more proteins
     *
     * Get a full sequence alignment of two or more proteins&lt;br/&gt;/alignment/protein/{proteins}/&lt;br/&gt;{proteins} is a comma separated list of protein identifiers, e.g. adrb2_human,5ht2a_human
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void proteinAlignmentGETTest() throws ApiException {
        String proteins = null;
        // Object response = api.proteinAlignmentGET(proteins);

        // TODO: test validations
    }
    
    /**
     * Get a partial sequence alignment of two or more proteins
     *
     * Get a partial sequence alignment of two or more proteins&lt;br/&gt;/alignment/protein/{proteins}/{segments}/&lt;br/&gt;{proteins} is a comma separated list of protein identifiers, e.g. adrb2_human,5ht2a_human&lt;br/&gt;{segments} is a comma separated list of protein segment identifiers and/ or     generic GPCRdb numbers, e.g. TM2,TM3,ECL2,4x50
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void proteinAlignmentPartialGETTest() throws ApiException {
        String proteins = null;
        String segments = null;
        // Object response = api.proteinAlignmentPartialGET(proteins, segments);

        // TODO: test validations
    }
    
    /**
     * Add a /statics at the end of an alignment in order to
     *
     * Add a /statics at the end of an alignment in order to      receive an additional residue property statistics output e.g.:&lt;br/&gt;/alignment/protein/{proteins}/{segments}/statistics&lt;br/&gt;{proteins} is a comma separated list of protein identifiers, e.g. adrb2_human,5ht2a_human&lt;br/&gt;{segments} is a comma separated list of protein segment identifiers and/ or     generic GPCRdb numbers, e.g. TM2,TM3,ECL2,4x50
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void proteinAlignmentStatisticsGETTest() throws ApiException {
        String proteins = null;
        // Object response = api.proteinAlignmentStatisticsGET(proteins);

        // TODO: test validations
    }
    
    /**
     * Add a /statics at the end of an alignment in order to
     *
     * Add a /statics at the end of an alignment in order to      receive an additional residue property statistics output e.g.:&lt;br/&gt;/alignment/protein/{proteins}/{segments}/statistics&lt;br/&gt;{proteins} is a comma separated list of protein identifiers, e.g. adrb2_human,5ht2a_human&lt;br/&gt;{segments} is a comma separated list of protein segment identifiers and/ or     generic GPCRdb numbers, e.g. TM2,TM3,ECL2,4x50
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void proteinAlignmentStatisticsGET_0Test() throws ApiException {
        String proteins = null;
        String segments = null;
        // Object response = api.proteinAlignmentStatisticsGET_0(proteins, segments);

        // TODO: test validations
    }
    
    /**
     * Get a segment sequence alignment of two or more proteins ranked by similarity
     *
     * Get a segment sequence alignment of two or more proteins ranked by similarity&lt;br/&gt;/alignment/similarity/{proteins}/&lt;br/&gt;{proteins} is a comma separated list of protein identifiers, e.g. adrb2_human,5ht2a_human,cxcr4_human,     where the first protein is the query protein and the following the proteins to compare it to&lt;br/&gt;{segments} is a comma separated list of protein segment identifiers and/ or     generic GPCRdb numbers, e.g. TM2,TM3,ECL2,4x50
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void proteinSimilaritySearchAlignmentGETTest() throws ApiException {
        String proteins = null;
        String segments = null;
        // ProteinSimilarities response = api.proteinSimilaritySearchAlignmentGET(proteins, segments);

        // TODO: test validations
    }
    
}
