/**
 * 
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package nl.esciencecenter.e3dchem.gpcrdb.client;

import nl.esciencecenter.e3dchem.gpcrdb.client.ApiException;
import nl.esciencecenter.e3dchem.gpcrdb.client.model.ProteinFamilySerializer;
import nl.esciencecenter.e3dchem.gpcrdb.client.model.ProteinSerializer;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ServicesproteinfamilyApi
 */
public class ServicesproteinfamilyApiTest {

    private final ServicesproteinfamilyApi api = new ServicesproteinfamilyApi();

    
    /**
     * Get a list of child families of a protein family
     *
     * Get a list of child families of a protein family&lt;br/&gt;/proteinfamily/children/{slug}/&lt;br/&gt;{slug} is a protein family identifier, e.g. 001_001_001
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void proteinFamilyChildrenListGETTest() throws ApiException {
        String slug = null;
        // ProteinFamilySerializer response = api.proteinFamilyChildrenListGET(slug);

        // TODO: test validations
    }
    
    /**
     * Get a list of descendant families of a protein family
     *
     * Get a list of descendant families of a protein family&lt;br/&gt;/proteinfamily/descendants/{slug}/&lt;br/&gt;{slug} is a protein family identifier, e.g. 001_001_001
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void proteinFamilyDescendantListGETTest() throws ApiException {
        String slug = null;
        // ProteinFamilySerializer response = api.proteinFamilyDescendantListGET(slug);

        // TODO: test validations
    }
    
    /**
     * Get a single protein family instance
     *
     * Get a single protein family instance&lt;br/&gt;/proteinfamily/{slug}/&lt;br/&gt;{slug} is a protein family identifier, e.g. 001_001_001
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void proteinFamilyDetailGETTest() throws ApiException {
        String slug = null;
        // ProteinFamilySerializer response = api.proteinFamilyDetailGET(slug);

        // TODO: test validations
    }
    
    /**
     * Get a list of protein families
     *
     * Get a list of protein families&lt;br/&gt;/proteinfamily/
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void proteinFamilyListGETTest() throws ApiException {
        // List<ProteinFamilySerializer> response = api.proteinFamilyListGET();

        // TODO: test validations
    }
    
    /**
     * Get a list of proteins in a protein family
     *
     * Get a list of proteins in a protein family&lt;br/&gt;/proteinfamily/proteins/{slug}/&lt;br/&gt;{slug} is a protein family identifier, e.g. 001_001_001
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void proteinsInFamilyListGETTest() throws ApiException {
        String slug = null;
        // List<ProteinSerializer> response = api.proteinsInFamilyListGET(slug);

        // TODO: test validations
    }
    
    /**
     * Get a list of proteins in a protein family
     *
     * Get a list of proteins in a protein family&lt;br/&gt;/proteinfamily/proteins/{slug}/{species}&lt;br/&gt;{slug} is a protein family identifier, e.g. 001_001_001&lt;br/&gt;{latin_name} is a species identifier from Uniprot, e.g. Homo sapiens
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void proteinsInFamilySpeciesListGETTest() throws ApiException {
        String slug = null;
        String latinName = null;
        // List<ProteinSerializer> response = api.proteinsInFamilySpeciesListGET(slug, latinName);

        // TODO: test validations
    }
    
}
