/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package nl.esciencecenter.e3dchem.gpcrdb.client;

import nl.esciencecenter.e3dchem.gpcrdb.client.ApiException;
import nl.esciencecenter.e3dchem.gpcrdb.client.model.ProteinSerializer;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ServicesproteinApi
 */
@Ignore
public class ServicesproteinApiTest {

    private final ServicesproteinApi api = new ServicesproteinApi();

    
    /**
     * Get a single protein instance by accession
     *
     * Get a single protein instance by accession&lt;br/&gt;/protein/accession/{accession}/&lt;br/&gt;{accession} is a protein identifier from Uniprot, e.g. P07550
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void proteinByAccessionDetailGETTest() throws ApiException {
        String accession = null;
        ProteinSerializer response = api.proteinByAccessionDetailGET(accession);

        // TODO: test validations
    }
    
    /**
     * Get a single protein instance by entry name
     *
     * Get a single protein instance by entry name&lt;br/&gt;/protein/{entry_name}/&lt;br/&gt;{entry_name} is a protein identifier from Uniprot, e.g. adrb2_human
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void proteinDetailGETTest() throws ApiException {
        String entryName = null;
        ProteinSerializer response = api.proteinDetailGET(entryName);

        // TODO: test validations
    }
    
}
