/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package nl.esciencecenter.e3dchem.gpcrdb.client;

import nl.esciencecenter.e3dchem.gpcrdb.client.ApiException;
import nl.esciencecenter.e3dchem.gpcrdb.client.model.SpeciesSerializer;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ServicesspeciesApi
 */
@Ignore
public class ServicesspeciesApiTest {

    private final ServicesspeciesApi api = new ServicesspeciesApi();

    
    /**
     * Get a single species instance
     *
     * Get a single species instance&lt;br/&gt;/species/{latin_name}/&lt;br/&gt;{latin_name} is a species identifier from Uniprot, e.g. Homo sapiens
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void speciesDetailGETTest() throws ApiException {
        String latinName = null;
        SpeciesSerializer response = api.speciesDetailGET(latinName);

        // TODO: test validations
    }
    
    /**
     * Get a list of species
     *
     * Get a list of species&lt;br/&gt;/species/
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void speciesListGETTest() throws ApiException {
        SpeciesSerializer response = api.speciesListGET();

        // TODO: test validations
    }
    
}
