/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package nl.esciencecenter.e3dchem.gpcrdb.client;

import nl.esciencecenter.e3dchem.gpcrdb.client.ApiException;
import nl.esciencecenter.e3dchem.gpcrdb.client.model.ResidueExtendedSerializer;
import nl.esciencecenter.e3dchem.gpcrdb.client.model.ResidueSerializer;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ServicesresiduesApi
 */
@Ignore
public class ServicesresiduesApiTest {

    private final ServicesresiduesApi api = new ServicesresiduesApi();

    
    /**
     * Get a list of residues of a protein, including alternative generic numbers
     *
     * Get a list of residues of a protein, including alternative generic numbers&lt;br/&gt;/residues/extended/{entry_name}/&lt;br/&gt;{entry_name} is a protein identifier from Uniprot, e.g. adrb2_human
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void residuesExtendedListGETTest() throws ApiException {
        String entryName = null;
        List<ResidueExtendedSerializer> response = api.residuesExtendedListGET(entryName);

        // TODO: test validations
    }
    
    /**
     * Get a list of residues of a protein
     *
     * Get a list of residues of a protein&lt;br/&gt;/residues/{entry_name}/&lt;br/&gt;{entry_name} is a protein identifier from Uniprot, e.g. adrb2_human
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void residuesListGETTest() throws ApiException {
        String entryName = null;
        List<ResidueSerializer> response = api.residuesListGET(entryName);

        // TODO: test validations
    }
    
}
